add feature windows to support windows
timvisee/qr2term-rs pull request #35
Opened 2024-09-05 15:20 UTC by teamplayer3

2024-09-05 15:24 UTC, timvisee requested changes

2024-09-05 15:24 UTC, timvisee commented on Cargo.toml
> +version = "0.3.3"
Please do not increase the version number here. That'll be done separately.

2024-09-05 15:24 UTC, timvisee commented on Cargo.toml
> +
Would it be better to enable this feature by default on Windows?

2024-09-05 15:44 UTC, teamplayer3 commented on Cargo.toml
> +
Yes, great idea.

2024-09-06 14:35 UTC, timvisee commented on Cargo.toml
> +
Yes, I had the option in your second link in mind.

It's not nice, but the best we can do for now.

2024-09-06 14:36 UTC, timvisee commented on Cargo.toml
> +
On second thought, it seems we can enable it by default in all cases, so also on non-Windows platforms. It seems that crossterm doesn't include any dependencies when the feature is set if compiling on non-Windows.

2024-09-12 11:56 UTC, teamplayer3 commented on Cargo.toml
> +
Great idea. I will look at it later this day.

2024-09-25 18:11 UTC, merged

2024-09-25 18:14 UTC, timvisee commented
@teamplayer3 Thanks for the PR!

I've just merged this and bumped the version to 0.3.3.

@mokurin000 The update should be available once this pipeline succeeds: https://gitlab.com/timvisee/qr2term-rs/-/pipelines/1469378504